env: "local"
http_server: 
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "12345678"
  dbname: "soft_hsm"
  sslmode: "disable"
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
