env: "local"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "12345678"
  dbname: "soft_hsm"
  sslmode: "disable"
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
jwt_config:
  secret: "ono"
  expires: 1440
  activation_secret: "yuko"
  activation_expires: 1440
  session_secret: "senko"
  session_expires: 5
mailer:
  email: "samgar.robot@gmail.com"
  password: "hsoi ubkd btow wkoa"
  smtp_host: "smtp.gmail.com"
  smtp_port: 587